### ISSUE TITLE
"pad = "  format attribute error

### ISSUE THREAD

**Issue by thilleary** [ShaneSutro/Vestaboard#25]
The following code has been reliably posting text strings or characters to our vestaboards:

###########################
def postit(payload):
    vboard.post(payload) 
###########################
# process raw characters to Vestaboard
############################
def SendRaw(characters):
    vboard.raw(characters, pad='center')

Lately however, the following error is received:

error in SendRaw
vboard.raw(characters, pad = 'center')
TypeError: raw() got an unexpected keyword argument 'pad'

This seemed to occur just about the time Vestaboard launched its VB+ applications. Any related causes here?

**Comment by ShaneSutro** [comment]
I’ll take a look! To my knowledge, this is unrelated - that bug seems to be almost pointing to a previous build, but I’ll take a look. I know this was awhile ago, but could you add the version of the library you have installed and the Python version you’re using?

**Comment by ShaneSutro** [comment]
Looks like this was an edge case that happened when the character list was exactly 6 rows! It was fixed in PR #24 by @jsdiaz - moving the re-formatting after the list length validation corrected the issue and also prevented unnecessary checks when the list was exactly 6 rows. This will be fixed in release v1.1.0!

**Comment by ShaneSutro** [comment]
Fixed in v1.1.0 release!
