### ISSUE TITLE
passing sub_id via vestaboard.Board() is broken

### ISSUE THREAD

**Issue by coreyzev** [ShaneSutro/Vestaboard#26]
**Describe the bug**
While attempting to initialize using just `vestaboard.Board()` and passing in Key, Secret, and SubID, I receive an error.

Calling the installable, and then passing that into the Board() works.

Works: 
```python
# Vestaboard
vesta_installable = vestaboard.Installable(VEST_API_KEY, VEST_API_SECRET)
vboard = vestaboard.Board(vesta_installable)
```
```python
# output
>>> vesta_installable
<vestaboard.Installable object at 0x000002B57EC26970>
```

Breaks:
```python
# Vestaboard
vboard = vestaboard.Board(VEST_API_KEY, VEST_API_SECRET, VEST_SUB_ID)
```
```
Exception has occurred: AttributeError
'str' object has no attribute 'apiKey'
  File "init.py", line 40, in <module>
    vboard = vestaboard.Board(VEST_API_KEY, VEST_API_SECRET, VEST_SUB_ID)
```

**Details**
Using VSCode Terminal on windows in a venv w/ Python 3

**Comment by ShaneSutro** [comment]
Hey thanks for this! Will take a look and see what I can spot. In a previous version we had the opposite of this problem where the line could not _end_ with a bracketed-character code, so this is likely something similar.

**Comment by ShaneSutro** [comment]
Okay I dug into this a bit! The issue is related to the arguments passed in.
In your code above, you're passing in three parameters. The signature for the board class allows this, but the first argument `Board()` is expecting is an instance of `Installable`:
![image](https://user-images.githubusercontent.com/36999012/174448984-784077ac-332e-4acd-8deb-c34aa2297ce9.png)
In your case you're passing the your API Key as the first argument. The `Board` constructor is trying to get access to the Installable's `.apiKey` property, but it's not an Installable, it's a string, thus the `'str' object has no attribute 'apiKey'`.

I will add a check/warning when a string is passed in instead of an `Installable` instance! In the meantime, you can fix this one of two ways:
1. Specify the argument names, or
2. Since `Installable` is optional, you can pass in `None` as the first argument
![image](https://user-images.githubusercontent.com/36999012/174449108-cb0a67c1-2245-4a92-99f4-6efa5eb705fc.png)
